plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}" apply false
	id 'me.fallenbreath.yamlang' version '1.5.0' apply false

	// https://github.com/Fallen-Breath/preprocessor
	id 'com.replaymod.preprocess' version 'c5abb4fb12'
}

preprocess {
	strictExtraMappings = false

	def mc1211 = createNode('1.21.1', 1_21_01, '')
	def mc1213 = createNode('1.21.3', 1_21_03, '')
	def mc1214 = createNode('1.21.4', 1_21_04, '')
	def mc1215 = createNode('1.21.5', 1_21_05, '')
	def mc1218 = createNode('1.21.8', 1_21_08, '')
	def mc12110 = createNode('1.21.10', 1_21_10, '')

	mc1211.link(mc1213, file('versions/mapping-1.21.1-1.21.3.txt'))
	mc1213.link(mc1214, file('versions/mapping-1.21.3-1.21.4.txt'))
	mc1214.link(mc1215, file('versions/mapping-1.21.4-1.21.5.txt'))
	mc1215.link(mc1218, file('versions/mapping-1.21.5-1.21.8.txt'))
	mc1218.link(mc12110, file('versions/mapping-1.21.8-1.21.10.txt'))

	for (final def node in getNodes()) {
		findProject(node.project).ext.mcVersion = node.mcVersion
	}
}

tasks.register('buildAndGather') {
	subprojects {
		dependsOn project.tasks.named('build').get()
	}
	doFirst {
		println 'Gathering builds'
		def buildLibs = { p -> p.buildDir.toPath().resolve('libs') }
		delete fileTree(buildLibs(rootProject)) {
			include '*'
		}
		subprojects {
			copy {
				from(buildLibs(project)) {
					include '*.jar'
					exclude '*-dev.jar', '*-sources.jar', '*-shadow.jar'
				}
				into buildLibs(rootProject)
				duplicatesStrategy = DuplicatesStrategy.INCLUDE
			}
		}
	}
}

// 让根项目 ./gradlew build 也能直接产出全部版本的 jar
if (!tasks.findByName('build')) {
	tasks.register('build') {
		dependsOn 'buildAndGather'
	}
} else {
	tasks.named('build') {
		dependsOn 'buildAndGather'
	}
}
