# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric build tools
# check these on https://fabricmc.net/develop
loom_version=1.15-SNAPSHOT
loader_version=0.18.4

# Mod Properties
mod_version=0.0.12
maven_group=xyz.water.rmatrix.cmod.craftguibelike
archives_base_name=carpet-jft-addition
